add_lunch_combo sabresd_6dq-eng
add_lunch_combo sabresd_6dq-userdebug
add_lunch_combo sabresd_6dq_car-eng
add_lunch_combo sabresd_6dq_car-userdebug
add_lunch_combo sabreauto_6q-eng
add_lunch_combo sabreauto_6q-userdebug
