#
# SoC-specific compile-time definitions.
#

BOARD_SOC_TYPE := IMX8Q
BOARD_HAVE_VPU := true
BOARD_VPU_TYPE := malone
HAVE_FSL_IMX_GPU2D := true
HAVE_FSL_IMX_GPU3D := true
HAVE_FSL_IMX_IPU := false
HAVE_FSL_IMX_PXP := false
BOARD_KERNEL_BASE := 0x80200000
TARGET_GRALLOC_VERSION := v3
TARGET_HIGH_PERFORMANCE := true
TARGET_USES_HWC2 := true
TARGET_HWCOMPOSER_VERSION = v2.0
TARGET_HAVE_VIV_HWCOMPOSER = false
TARGET_FSL_IMX_2D := DPU2D
USE_OPENGL_RENDERER := true
TARGET_CPU_SMP := true
TARGET_HAVE_VULKAN := true
ENABLE_CFI=false

# enable opencl 2d.
TARGET_OPENCL_2D := true
